#!/usr/bin/env python

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'src'))

import application


if __name__ == '__main__':
    app = application.Application()
